---
language: ruby
rvm:
  - 2.5

jobs:
  include:
    #################
    ### validation ##
    #################
    - stage: validation
      name: "version"
      script: ruby -e "require './lib/qat/logger/version'; raise StandardError.new unless Gem::Specification::load('qat-logger.gemspec').version.to_s == QAT::Logger::VERSION"
      if: branch != master AND tag IS blank
    ###############
    ### analysis ##
    ###############
    - stage: analysis
      name: "documentation"
      script: bundle exec rake qat:devel:validate_yard_doc
      if: branch != master AND tag IS blank
    - name: "static"
      script: bundle exec rake qat:devel:static_analysis:validation
      if: branch != master AND tag IS blank
    ###########
    ### test ##
    ###########
    - stage: test
      name: "unit tests"
      script: bundle exec rake qat:devel:tests:run
    ############
    ### build ##
    ############
    - stage: build
      name: "build gem"
      script: gem build *.gemspec
    ##############
    ### release ##
    ##############
    - stage: release
      name: "gem release"
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        gemspec: *.gemspec
      if: branch = master AND tag IS present

stages:
  - validation
  - analysis
  - test
  - build
  - release