---
language: ruby
rvm:
  - 2.5

jobs:
  include:
    #################
    ### validation ##
    #################
    - stage: validation
      name: "version"
      script: ruby -e "require './lib/qat/devel/version'; raise StandardError.new unless Gem::Specification::load('qat-devel.gemspec').version.to_s == QAT::Devel::VERSION"
      if: branch != master AND tag IS blank
    ###############
    ### analysis ##
    ###############
    - stage: analysis
      name: "documentation"
      script: bundle exec rake qat:devel:validate_yard_doc
      if: branch != master AND tag IS blank
#      #TODO: Check GitHub pages
#      addons:
#        artifacts:
#          paths:
#            - doc/
    - name: "static"
      script: bundle exec rake qat:devel:static_analysis:html
      script: bundle exec rake qat:devel:static_analysis:validation
      if: branch != master AND tag IS blank
#      #TODO: Check GitHub pages
#      addons:
#        artifacts:
#          paths:
#            - test/public/rubycritic/

    ###########
    ### test ##
    ###########
    - stage: test
      name: "unit tests"
      script: bundle exec rake qat:devel:tests:run
      if: branch != master AND branch != develop AND tag IS blank
      addons:
        artifacts:
          paths:
            - test/public/index.html
            - test/coverage/
    ############
    ### build ##
    ############
#    - stage: build
#          script: gem build qat-reporter-xray.gemspec
#          if: branch = develop AND tag IS present
#          addons:
#            artifacts:
#              paths:
#                - qat-reporter-xray-*.gem

    ##############
    ### release ##
    ##############
    - stage: release
      name: "gem release"
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        gemspec: qat-reporter-xray.gemspec
      if: branch = master AND tag IS present


stages:
  - validation
  - analysis
  - test
  #- build
  - release